### ISSUE TITLE
can NOT compile 

### ISSUE THREAD

**Issue by SIDRONA73** [studioraz/magento2-unicode-url#4]
After insall  magento2-unicode-url  using composer install

RUN:  php bin/magento setup:di:compile

RESULTS:

/var/www/html$ php bin/magento setup:di:compile
Compilation was started.
Repositories code generation... 1/9 [===>------------------------]  11% < 1 sec 129.0 MiB
There is an error in /var/www/html/vendor/studioraz/magento2-unicode-url/Filter/AbstractTranslitUrl.php at line: 12
Interface "Zend_Filter_Interface" not found#0 /var/www/html/vendor/composer/ClassLoader.php(571): include()
#1 /var/www/html/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#2 /var/www/html/vendor/studioraz/magento2-unicode-url/Filter/TranslitUrlProduct.php(10): Composer\Autoload\ClassLoader->loadClass()
#3 /var/www/html/vendor/composer/ClassLoader.php(571): include('...')
#4 /var/www/html/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#5 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#6 /var/www/html/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(134): class_exists()
#7 /var/www/html/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(117): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->includeClass()
#8 /var/www/html/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(87): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->extract()
#9 /var/www/html/setup/src/Magento/Setup/Module/Di/App/Task/Operation/RepositoryGenerator.php(61): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->getList()
#10 /var/www/html/setup/src/Magento/Setup/Module/Di/App/Task/Manager.php(56): Magento\Setup\Module\Di\App\Task\Operation\RepositoryGenerator->doOperation()
#11 /var/www/html/setup/src/Magento/Setup/Console/Command/DiCompileCommand.php(209): Magento\Setup\Module\Di\App\Task\Manager->process()
#12 /var/www/html/vendor/symfony/console/Command/Command.php(298): Magento\Setup\Console\Command\DiCompileCommand->execute()
#13 /var/www/html/vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#14 /var/www/html/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#15 /var/www/html/vendor/magento/framework/Console/Cli.php(116): Symfony\Component\Console\Application->doRun()
#16 /var/www/html/vendor/symfony/console/Application.php(171): Magento\Framework\Console\Cli->doRun()
#17 /var/www/html/bin/magento(23): Symfony\Component\Console\Application->run()
#18 {main}

**Comment by SIDRONA73** [comment]
this fixed it. https://github.com/studioraz/magento2-unicode-url/compare/master...Peerapatfc:magento2-unicode-url:master
